### ISSUE TITLE
使用-w方式打包会报错

### ISSUE THREAD

**Issue by fldsjls** [taojy123/KeymouseGo#194]
![屏幕截图 2022-12-17 213716](https://user-images.githubusercontent.com/120763618/208244680-5bd27ef0-73d6-4cd9-b255-bd32664d67f7.png)
最后我尝试使用传统的-c打包方式可以运行

**Comment by nAnderYang** [comment]
同样的错误。

**Comment by nAnderYang** [comment]
```
Traceback (most recent call last):
  File "KeymouseGo.py", line 11, in <module>
  File "C:\Users\nAnder\AppData\Local\Temp\embedded.p6rbo2qm.zip\shibokensupport\__feature__.py", line 142, in _import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "UIFunc.py", line 41, in <module>
  File "loguru\_logger.py", line 830, in add
TypeError: Cannot log to objects of type 'NoneType'
```

**Comment by bingfengfeifei** [comment]
问题出在UIFunc.py的41行
```python
logger.add(sys.stdout, backtrace=True, diagnose=True, level='DEBUG')
```
该行是给DEBUG调试logger添加一个handler，但是输出的目标是stdout。 而使用-w打包的时候纯GUI程序的sys.stdout是None，所以出现了该错误，在打包GUI程序的时候可以将该行注释掉

**Comment by nAnderYang** [comment]
@bingfengfeifei 多谢 学习了 问题解决
