### ISSUE TITLE
最新release安装失败 win11

### ISSUE THREAD

**Issue by Byc4i** [taojy123/KeymouseGo#201]
报错：
Traceback (most recent call last):
  File "KeymouseGo.py", line 148, in <module>
  File "KeymouseGo.py", line 55, in main
  File "UIFunc.py", line 119, in __init__
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by Monomux** [comment]
是配置文件参数读取问题，可以检查一下程序目录下的`config.ini`文件参数格式是否正常，或者你可以删除`config.ini`文件并重新运行程序。
```ini
[Config]
; int
StartHotKeyIndex=3
; int
StopHotKeyIndex=12
; int
RecordHotKeyIndex=7
; int
LoopTimes=1
; int
Precision=200
; str
Language=zh-cn
; str
Extension=Extension
; str
Script=script.txt
```

**Comment by Goooler** [comment]
还是不行
