### ISSUE TITLE
ArchLinux下运行报错

### ISSUE THREAD

**Issue by zxp19821005** [taojy123/KeymouseGo#259]
OS : EndeavourOS
Kernel : 6.1.57-1-lts
DM : lightdm 1:1.32.0-4
xorg : xorg-server 21.1.8-2
运行后报错如下：
```
$ keymousego
Traceback (most recent call last):
  File "KeymouseGo.py", line 11, in <module>
  File "/tmp/embedded.p07l1p0n.zip/shibokensupport/__feature__.py", line 142, in _import
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "UIFunc.py", line 11, in <module>
  File "/tmp/embedded.p07l1p0n.zip/shibokensupport/__feature__.py", line 142, in _import
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "Recorder/__init__.py", line 8, in <module>
  File "/tmp/embedded.p07l1p0n.zip/shibokensupport/__feature__.py", line 142, in _import
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "Recorder/UniversalRecorder.py", line 3, in <module>
  File "/tmp/embedded.p07l1p0n.zip/shibokensupport/__feature__.py", line 142, in _import
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pynput/__init__.py", line 40, in <module>
  File "/tmp/embedded.p07l1p0n.zip/shibokensupport/__feature__.py", line 142, in _import
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pynput/keyboard/__init__.py", line 31, in <module>
  File "pynput/_util/__init__.py", line 82, in backend
ImportError: this platform is not supported: No module named 'pynput.keyboard._xorg'

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
[218682] Failed to execute script 'KeymouseGo' due to unhandled exception!
```

**Comment by Monomux** [comment]
>Try one of the following resolutions:
>* Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly

根据报错里面的提示设置一下试试？

**Comment by xpaxp** [comment]
deepin 20.9同样情况，设置export DISPLAY=:0.0后，也是这样报错

**Comment by waniani** [comment]
我在manjaro 中执行也有相似的输出，是因为什么吗，有解决的吗
Kernel: 6.6.32-1-MANJARO 

```
    ~/Downloads  DISPLAY=:0 ./KeymouseGo_v5_1_1-linux                                          INT ✘  1m 47s  
/bin/sh: symbol lookup error: /bin/sh: undefined symbol: rl_trim_arg_from_keyseq
Traceback (most recent call last):
  File "KeymouseGo.py", line 11, in <module>
  File "/tmp/embedded.40_fa64q.zip/shibokensupport/__feature__.py", line 142, in _import
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "UIFunc.py", line 11, in <module>
  File "/tmp/embedded.40_fa64q.zip/shibokensupport/__feature__.py", line 142, in _import
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "Recorder/__init__.py", line 8, in <module>
  File "/tmp/embedded.40_fa64q.zip/shibokensupport/__feature__.py", line 142, in _import
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "Recorder/UniversalRecorder.py", line 3, in <module>
  File "/tmp/embedded.40_fa64q.zip/shibokensupport/__feature__.py", line 142, in _import
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pynput/__init__.py", line 40, in <module>
  File "/tmp/embedded.40_fa64q.zip/shibokensupport/__feature__.py", line 142, in _import
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pynput/keyboard/__init__.py", line 31, in <module>
  File "pynput/_util/__init__.py", line 82, in backend
ImportError: this platform is not supported: No module named 'pynput.keyboard._xorg'

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
[4655] Failed to execute script 'KeymouseGo' due to unhandled exception!

```

**Comment by tksmly** [comment]
https://stackoverflow.com/questions/63681770/getting-error-when-using-pynput-with-pyinstaller
