### ISSUE TITLE
Can it click in specific window?

### ISSUE THREAD

**Issue by dasiuk** [taojy123/KeymouseGo#264]
Hey man! I don't know, can I choose a window I want it to click in? From the list of processes?

Also when trying to install on windows 10 pro I get this error:
![image](https://github.com/taojy123/KeymouseGo/assets/78763630/13032c43-aaee-4003-ad3c-ee4c6c09cf40)

**Comment by dasiuk** [comment]
Traceback (most recent call last):
  File "KeymouseGo.py", line 148, in <module>
  File "KeymouseGo.py", line 55, in main
  File "UIFunc.py", line 119, in __init__
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by Monomux** [comment]
Currently this program couldn't work merely on a specific window. 😢 

>Traceback (most recent call last):
File "KeymouseGo.py", line 148, in
File "KeymouseGo.py", line 55, in main
File "UIFunc.py", line 119, in init
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Please check if the value of `StopHotKeyIndex` in `config.ini` is a number, or you can delete `config.ini` in the work directory and restart the program.

**Comment by dasiuk** [comment]
Thanks! Np, hope I'll find specific window clicker some day
