### ISSUE TITLE
MAC下启动报错KeyError: 'CFMachPortCreateRunLoopSource'

### ISSUE THREAD

**Issue by innerbboy** [taojy123/KeymouseGo#279]
错误信息如下：
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/daiyunshan/gitproject/KeymouseGo/venv/lib/python3.11/site-packages/pynput/_util/__init__.py", line 210, in run
    self._run()
  File "/Users/daiyunshan/gitproject/KeymouseGo/venv/lib/python3.11/site-packages/pynput/keyboard/_darwin.py", line 254, in _run
    super(Listener, self)._run()
  File "/Users/daiyunshan/gitproject/KeymouseGo/venv/lib/python3.11/site-packages/pynput/_util/darwin.py", line 202, in _run
    loop_source = Quartz.CFMachPortCreateRunLoopSource(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daiyunshan/gitproject/KeymouseGo/venv/lib/python3.11/site-packages/objc/_lazyimport.py", line 178, in __getattr__
    value = getattr(p, name)
            ^^^^^^^^^^^^^^^^
  File "/Users/daiyunshan/gitproject/KeymouseGo/venv/lib/python3.11/site-packages/objc/_lazyimport.py", line 178, in __getattr__
    value = getattr(p, name)
            ^^^^^^^^^^^^^^^^
  File "/Users/daiyunshan/gitproject/KeymouseGo/venv/lib/python3.11/site-packages/objc/_lazyimport.py", line 192, in __getattr__
    value = get_constant(name)
            ^^^^^^^^^^^^^^^^^^
  File "/Users/daiyunshan/gitproject/KeymouseGo/venv/lib/python3.11/site-packages/objc/_lazyimport.py", line 360, in get_constant
    funcmap.pop(name)
KeyError: 'CFMachPortCreateRunLoopSource'

**Comment by ZhengGong-hub** [comment]
我也是这个错。请问你现在debug出来了吗? 谢谢

**Comment by Monomux** [comment]
我在MacOS Sonoma 14.0虚拟机上并不能复现出这个问题。看日志是上游依赖pynput的问题，你可以尝试将pynput更新至1.7.7以上的版本试试。

上游相关 issue
https://github.com/moses-palmer/pynput/issues/55
https://github.com/moses-palmer/pynput/issues/597
