### ISSUE TITLE
win10运行exe文件报错

### ISSUE THREAD

**Issue by bkzy333** [taojy123/KeymouseGo#281]
![2024-03-09_213746](https://github.com/taojy123/KeymouseGo/assets/85782080/b30da148-9b6b-4535-af1d-25181acf1199)

文件名：KeymouseGo_v5_1_1-win.exe
双击运行后，报错内容如下：
Traceback (most recent call last):
  File "KeymouseGo.py", line 148, in <module>
  File "KeymouseGo.py", line 54, in main
  File "UIFunc.py", line 120, in __init__
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by xiaoyaolanyun** [comment]
遇到同样问题

**Comment by Monomux** [comment]
配置文件有问题，检查或删除同目录下config.ini文件试试。

**Comment by THEWINDRUNNERLIFE** [comment]
> 配置文件有问题，检查或删除同目录下config.ini文件试试。

确实已解决，是其他工具的cofig.ini影响到了，换个空目录后就好了
